#!/usr/bin/awk -f
BEGIN {FS=" *, *"; OFS=","}
NR==FNR {
    gsub(/"/, "", $2);
    MAP[$2]=$1;
    next;
}

{
    CA=MAP[$1];
    CB=MAP[$2];

    if (!CA) { CA="*" $1 }
    if (!CB) { CB="*" $2 }
    print CA,CB,$3;
}
