#!/usr/bin/gawk -f
BEGIN {
    FS=";";    
}

/^#/ { next }

{
    A[$1][$2]["*"]=$3;
    for(i = 4; i <= NF; ++i) {
        split($i, lang, /=/);
        A[$1][$2][lang[1]] = lang[2];
    }
}

END {
    printf("{");
    N=0;
    for (c in A) {
        if (N++) { printf(",") };
        printf("\n  \"%s\": {", c);
        F=0;
        for(k in A[c]) {
            if (F++) { printf(",") };
            printf(" \"%s\": {", k);
            L=0;
            for(l in A[c][k]) {
                if (L++) { printf(",") };
                printf(" \"%s\": \"%s\"", l, A[c][k][l]);
            }
            printf(" }");
        }
        printf(" }");
    }
    printf("\n}\n");
}
