#!/usr/bin/awk -f
BEGIN {
    FS=OFS=",";    
}

/^#/ { next }

FNR==NR {
    STORE[$1]=$2;
    FEATURE[$1]=$3;
    next;
}

{
    if (!$1 in COUNTRIES) {
        del tmp;
        tmp["D/C"]="";
        tmp["P/C"]="";

        COUNTRIES[$1]=tmp;
    }

    if ($2 in STORE) {
        if (index(FEATURE[$2],"D") && (!COUNTRY[$1]["D/C"] || COUNTRY[$1]["D/D"] > $3)) {
            COUNTRY[$1]["D/C"] = STORE[$2];
            COUNTRY[$1]["D/D"] = $3;
        }
        if (index(FEATURE[$2],"P") && (!COUNTRY[$1]["P/C"] || COUNTRY[$1]["P/D"] > $3)) {
            COUNTRY[$1]["P/C"] = STORE[$2];
            COUNTRY[$1]["P/D"] = $3;
        }
    }
}

END {
    for(c in COUNTRY) {
        print c,"P",COUNTRY[c]["P/C"],COUNTRY[c]["P/D"];
        print c,"D",COUNTRY[c]["D/C"],COUNTRY[c]["D/D"];
    }
}
