#!/usr/bin/gawk -f
BEGIN {
    FS=";";    
}

/^#/ { next }

{
    A[$1]=$3;
}

END {
    printf("{");
    N=0;
    for (c in A) {
        if (N++) { printf(",") };
        printf("\n  \"%s\": \"%s\"", c, A[c]);
    }
    printf("\n}\n");
}
